steps:
  # ステップ1: Dockerイメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image", "."]

  # ステップ2: ビルドしたイメージをGoogle Container Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-image"]

# イメージをGoogle Container Registryにプッシュする際のタグ
images:
  - "gcr.io/$PROJECT_ID/my-image"

# （オプション）ビルドログの設定
# 以下はビルドログをCloud Storageの指定バケットに保存する例です
options:
  logging: "CLOUD_LOGGING_ONLY"
# logsBucket: 'gs://my-logs-bucket'
